[project]
name = "turtles"
version = "0.1.0"
description = "Pythonic parser tools"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.optional-dependencies]
lark = [
    "lark>=1.3.1",
]
all = [
    "lark>=1.3.1",
]
